apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-content
  labels:
    app: ai-content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-content
  template:
    metadata:
      labels:
        app: ai-content
    spec:
      containers:
        - name: ai-content
          image: asia-south1-docker.pkg.dev/PROJECT/containers/ai-content:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ai-content-svc
  labels:
    app: ai-content
spec:
  selector:
    app: ai-content
  ports:
    - name: http
      port: 80
      targetPort: 5001
  type: LoadBalancer
